### PR TITLE
Add perl access to pl_cmd and ability to set Cairo context

### PR DESCRIPTION
**Pull request by mikef5410**
With this patch we can set the cairo context, and therefore embed a plplot graphic in a Gtk3 widget.

### CODE REVIEW

**Comment by mohawk2** [comment]
Just for starters, you need to `git rm META.*` :-)

**Comment by mohawk2** [comment]
I see you have a number of (colossally large) files that seem to be demos, but are in the `t` directory? Surely that's not what you intend?

**Comment by mikef5410** [comment]
Commit 905002 is the "interesting" change, and it only involves plplot.pd

Sorry, I don't see the big files you're talking about.

**Comment by mohawk2** [comment]
Fair enough. If you look at this page, you will see large files. If you intend only to merge one commit, could you rebase and force-push your branch such that it's the only commit in this PR? Although that does beg the question as to why the author of the repo, Doug Hunt, isn't using this repo to track changes.

**Comment by mohawk2** [comment]
In fact, I have emailed him to ask.

**Comment by zmughal** [comment]
CC @doughunt.

**Comment by mohawk2** [comment]
Hi @mikef5410, I've rebased this commit onto latest master. Since I don't have permission to force-push to your branch, I've pushed it to the `CairoContext` branch of this repo.

Is this change one you're still interested in? Would it make more sense to have it in a subclass of P::G::PLplot, in which case you could release it yourself? Also, if you *are* still interested, please write some tests for it :-)

**Comment by mikef5410** [comment]
Yes, please. It is not special purpose and should go into the main product.   I'll look into what can be tested and add to my Cairo context branch and ask for a second pull.
thanks!
-Mike

**Comment by mohawk2** [comment]
No need to make a second PR, you can use this one. All you need to do is:

```
git remote add upstream git@github.com:PDLPorters/pdl-graphics-plplot.git
git fetch --all
git checkout CairoContext
git reset --hard upstream/CairoContext
git push -f
```

which will switch you to my rebased version. Then you can add tests, and so on!

**Comment by mikef5410** [comment]
Cool. Will do. Thanks again.

**Comment by mohawk2** [comment]
I have merged this change and released it as 0.76. There are no tests so there is no guarantee it works correctly.

**Pull request closed without merging**
