### PR TITLE
gh switch

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by devel-chm** [comment]
Looks good to me.

**Comment by mohawk2** [comment]
@doughunt Any thoughts? Also, how do you feel about making me co-maint and/or transferring ownership of the module?

**Comment by doughunt** [comment]
Hi Mohawk:  I would be open to the idea of co-maintainership of 
PDL::Graphics::PLplot.  I have not had time
to keep it up-to-date in the last few years.

Regards,

   Doug Hunt

**Comment by mohawk2** [comment]
I'll be happy to take co-maint. If you really don't have time anymore, you could even make me the "first-come", so I could hand it on in due course. In any case, I'm "ETJ" on PAUSE :-)

**Pull request merged**
